version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: assignment
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    container_name: api_container
    ports:
      - "8081:80"
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  mysql_data: