services:
#  mysql_assignment:
#    image: mysql:8.0
#    container_name: mysql
#    environment:
#      MYSQL_USER: assignment
#      MYSQL_ROOT_PASSWORD: 123456
#      MYSQL_PASSWORD: 123456
#      MYSQL_DATABASE: assignment
#    ports:
#      - "3310:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    container_name: api_container
    ports:
      - "8081:80"
#    depends_on:
#      - mysql_assignment
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

#volumes:
#  mysql_data: