# This is a generated file. Not intended for manual editing.
services:
  api:
    build:
      context: "D:\\New folder\\vng-assignment"
      dockerfile: "API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net6.0/API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "api:dev"
    ports: []
    volumes:
    - "C:\\Users\\ASUS\\.nuget\\packages:/root/.nuget/packages"
    - "D:\\New folder\\vng-assignment\\API:/app:rw"
    - "D:\\New folder\\vng-assignment:/src:rw"
    working_dir: "/app"
